# Generated by Django 4.2.23 on 2025-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_tickerviewcount_viewhistory_stockdata_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='페이지뷰')),
                ('unique_visits', models.PositiveIntegerField(default=0, verbose_name='고유방문자')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='마지막 업데이트')),
            ],
            options={
                'verbose_name': '일별 접속 통계',
                'verbose_name_plural': '일별 접속 통계',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='접속일')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='접속시간')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='페이지뷰')),
                ('unique_visits', models.PositiveIntegerField(default=0, verbose_name='고유방문자')),
            ],
            options={
                'verbose_name': '사이트 접속 통계',
                'verbose_name_plural': '사이트 접속 통계',
                'ordering': ['-visit_date'],
            },
        ),
    ]
