# Generated by Django 4.2.23 on 2025-09-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_dailyvisit_sitevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyVisit',
        ),
        migrations.DeleteModel(
            name='SiteVisit',
        ),
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
